### ISSUE TITLE
HISTORY_LIMIT not respected

### ISSUE THREAD

**Issue by AdamSLevy** [yulrizka/git-checkout-history#2]
Thanks for the script. I am finding it very useful.

I had to change line 19 to get HISTORY_LIMIT working by adding the `--max-count` argument to grep.
```
  # filter only valid branch
  local valid_branch
  valid_branch=$(echo "$branches" | grep --max-count $HISTORY_LIMIT -f <(git branch -a | sed 's/^  //; s/^* //; s/^remotes\///; s/\(.*\) -> .*/\1/;'))
```

**Comment by yulrizka** [comment]
Thanks for the feedback! added it to the script
